### ISSUE TITLE
The update today seems to have broke it.

### ISSUE THREAD

**Issue by mattharper8** [matextrem/streamdeck-tickertap#1]
**Describe the bug**
Tickets don't work.  Period end of story.

**To Reproduce**
Try to load a new ticket or look at an existing one.

**Expected behavior**
I expect it to work.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by matextrem** [comment]
Hey @mattharper8 ! I've just downloaded it and it's working fine for me. Have you tried reinstalling it ?

**Comment by mattharper8** [comment]
Uninstalling and reinstalling fixed it.  Thanks!
