### ISSUE TITLE
[FEATURE] Add European ETFs

### ISSUE THREAD

**Issue by Lerwox** [matextrem/streamdeck-tickertap#12]
**Is your feature request related to a problem? Please describe.**
You recently added europeen stock, but we cannot use etfs from investing.com, that's not the same url. It will be nice if we could choose between stock and ETF

**Describe the solution you'd like**
Choose between stock and ETF

**Describe alternatives you've considered**
I've thought about hard-coding the urls, but I suppose that's not the only impact, and that all the APIs are different.

**Additional context**

**Comment by matextrem** [comment]
Hey @Lerwox ! I'll consider adding this for the next release. Thanks for the feedback!

**Comment by matextrem** [comment]
Hey @Lerwox ! I've released v1.2.1 version with support for ETFs. You can download it from [here](https://github.com/matextrem/streamdeck-tickertap/releases/tag/v1.2.1) 

LMK if it works for you.

**Comment by Lerwox** [comment]
Hey @matextrem,

I tried it, and it works perfectly, I also could add param request in the URL, so it's possible to have ETF in a certain exchange.

Examples : 
- https://www.investing.com/etfs/spdr-msci-world-ucits-lse-usd?cid=1165086 → spdr-msci-world-ucits-lse-usd?cid=1165086
- https://www.investing.com/etfs/spdr-msci-world-ucits-lse-usd → spdr-msci-world-ucits-lse-usd

These two tickers, works like magic.

Thank you very much !
