### ISSUE TITLE
I have a suggestion.

### ISSUE THREAD

**Issue by phoenixlhj** [matextrem/streamdeck-tickertap#14]
Your wonderful plug-in is making my stock easier.
There is one thing I would like to suggest.
I use your plug-in in Korea and in the Korean stock market, they express it in red when it goes up and blue when it goes down.
I would like to suggest adding an option to change the color for the rise or fall.
I'm very happy to have access to your awesome plug-in and I'm honored if you accept my suggestions positively.
Thank you.

**Comment by matextrem** [comment]
Hey @phoenixlhj! Thanks for your suggestion, it's really valuable for us. We'll be adding this feature in our new release for sure. I'll let you know when it's ready to download.

**Comment by matextrem** [comment]
Hey @phoenixlhj ! 1.3.0 version has been released with support for changing the rising/falling stock colors. You can download it from [here](https://github.com/matextrem/streamdeck-tickertap/releases/tag/v1.3.0) 

Let me know if it works for you 😄

**Comment by phoenixlhj** [comment]
It works so well!
Thank you for listening to the small comments.
