### ISSUE TITLE
Dow Jones, Nasdaq, etc. - clarification

### ISSUE THREAD

**Issue by uded** [matextrem/streamdeck-tickertap#15]
Found some [constants ](https://github.com/matextrem/streamdeck-tickertap/blob/68e910392c85275e4d28a7a50505ce9ee1e5f6cc/src/helpers/constants.ts#L311) for this, but still can't make it to work. It would be nice to clarify how to achieve a Nasdaq Composite (IXIC) or Dow Jones indices listing.

**Comment by matextrem** [comment]
Hey @uded ! Thank you for raising the issue. 

We've found out a bug in the code which caused these tickers to not working properly. We've just released a new version with the fix. You can download it from here: https://github.com/matextrem/streamdeck-tickertap/releases/tag/v1.4.1


So now you'll be able to access those tickers as follows: 

Nasdaq Composite - > **IXIC**
Industrial Dow Jones -> **DJI**

Type must be set to **Stock** and Market to **America**

Let me know if it works for you now. 

Thanks!

**Comment by matextrem** [comment]
@uded I'll let the ElGato team know about this but it can take several days for them to be published

**Comment by matextrem** [comment]
Hey @uded, `v1.7.0` has been released in the Elgato Marketplace webpage so you can download it from there 😃

**Comment by uded** [comment]
Thank you, that made my life much easier. Much appreciated!

BTW, is it so difficult to update plugins with Elgato? This task, at least theoretically, should be relatively straightforward.

**Comment by matextrem** [comment]
@uded  The process to upload a new version was to send an email with the update to the Elgato team and wait for them to review and publish it. 

Fortunately, they've just released a new feature that allow contributors to upload their plugin versions using a platform, so it seems it'll be more straightforward from now on.

**Comment by uded** [comment]
Thank you, I really appreciate the info! 

I'm considering publishing one of my plugins, but never bothered to check the process...
