### ISSUE TITLE
Unable to add Finviz 10 Year Note Futures ZN

### ISSUE THREAD

**Issue by robert-reiser** [matextrem/streamdeck-tickertap#17]
Hi - thank you for creating and sharing this wonderful plugin with us.

Quick question: I have already successfully added Futures from Finviz as described in the README, for example ES and NQ. However, when I try to add the 10-Year Note Futures (symbol: ZN on Finviz, https://finviz.com/futures_charts.ashx?t=ZN), I only briefly see a warning triangle.

I have used "ZN" as ticker and "Futures" as category, using other categories doesn't work either. Any ideas why this specific Future doesn't work?

I am using the latest plugin version 1.5.0, released very recently.

Thank you very much in advance,

Robert

**Comment by Madso02** [comment]
Hey @robert-reiser! I haven't developed this plugin, but looking at the code, futures actually only support indicies, which is why ES and NQ works. The 10-Year Note Futures is a bond, so the plugin currently does not support it.
Maybe bonds can be added? @matextrem

**Comment by matextrem** [comment]
Exactly @Madso02. Currently BONDS are not supported by the plugin. We could add a new type in order to add support for this

cc: @robert-reiser

**Comment by robert-reiser** [comment]
Understood, to me it looked like a Future contract. Thank you for the consideration to support Bonds at some point in the future!

**Comment by matextrem** [comment]
Hey @robert-reiser! We've released v1.7.0 which adds supports for Bonds. You can download it from [here](https://github.com/matextrem/streamdeck-tickertap/releases/tag/v1.7.0)

Let me know if it works for you. 

Regards,

Mati

**Comment by robert-reiser** [comment]
Mati, I am simply stunned... never seen a feature request being handled so quickly. It works perfectly, thank you!

Really appreciate your support.

Kind regards,

Robert
