### ISSUE TITLE
Add indices like SPX or NDX?

### ISSUE THREAD

**Issue by viper549** [matextrem/streamdeck-tickertap#20]
Hi,

great plugin but I miss the option to add indices like SPX, NDX, DJI,...

Any possibility to get this?

Thanks
Marcel

**Comment by matextrem** [comment]
Hey @viper549! They are already supported by the plugin. 

SPX - > Select Stock type and use SPX as ticker
DJI -> Select Stock type and use DJI as ticker
NDX -> Nasdaq 100 is being shown in Finviz as NQ. So you have to select Stock type and use NQ as ticker

**Comment by viper549** [comment]
Hi @matextrem,

thanks for you fast replay, but it's not working for me. 

I use this setting
![image](https://github.com/user-attachments/assets/873befcc-dc87-400a-9fec-7663f72155ec)

Do I set something wrong? I just receive the yellow triangle. 

Thx Viper

**Comment by viper549** [comment]
@matextrem thanks, I updated to v1.7.0 and it works fine. thanks a lot for that great plugin.
