### ISSUE TITLE
No Support for Indian Stock

### ISSUE THREAD

**Issue by Rajat72** [matextrem/streamdeck-tickertap#21]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by matextrem** [comment]
Hey @Rajat72! The plugin is already supporting Indian stock market. You need to select `Asia/Pacific` option in `Region` field.

**Comment by Rajat72** [comment]
i was trying with Asia/Pacific option in Region field.

**Comment by matextrem** [comment]
@Rajat72 Which stock are you trying with?
