### ISSUE TITLE
For forex an ability to decide on how many decimals points are there

### ISSUE THREAD

**Issue by uded** [matextrem/streamdeck-tickertap#22]
This is specific to FOREX, as currencies' volatility and trading range usually revolve around 4th or 5th place after a comma. I am happy to sacrifice the green/red arrow (but not the colors of percentage change) to get any value out of... well, currency value. Four or five decimal points are needed. 

I would like to give you an example. The daily trading range of the EURUSD pair is between 1.08243 and 1.07978 today. Rounding up a change of 1.082 to 1.081 might happen multiple times during the day and tells me nothing about what is happening there. I need to see a 5-minute drop from 1.08243 to 1.08217. For the ticker, it's still 1.082, and the percentage change is shown since the last day of trading, I believe. It tells me... nothing.

I may be asking for too much, as it may require a different plugin designed for FOREX. Still, it would be nice to decide this in the config of each ticker OR have this predefined for FOREX since it's a universal way of showing currency values...

**Comment by matextrem** [comment]
Hey @uded! Absolutely. This is something we'll take into consideration for the next release.

**Comment by uded** [comment]
I installed 1.8.0, but it still shows me four decimal digits.

![image](https://github.com/user-attachments/assets/b39cbc38-09bd-44af-9b1b-0584a2649999)
![image](https://github.com/user-attachments/assets/46061523-1496-4a47-86b4-e83f035ddfc7)

**Comment by matextrem** [comment]
Hey @uded, We're using investing.com as a provider and it's returning 4 decimals...

https://uk.investing.com/currencies/usd-pln

**Comment by uded** [comment]
OK, that sucks big time. On FOREX, those ticks between 4 and 5 digits are crucial and make a lot of difference...
But I get it. Most APIs, even the free ones, require registration, which is tedious for users.
