### ISSUE TITLE
AZO stock incorrect

### ISSUE THREAD

**Issue by minnecrapolis** [matextrem/streamdeck-tickertap#24]
Added stck symbol AZO (Autozone).

Price shows as 3.00 when actual price is 3,097.45

**Comment by matextrem** [comment]
Hi @minnecrapolis! Thank you so much for your feedback. We've found a formatting issue for numbers bigger than 1000 (period sign present). 

We'll be addressing it ASAP and publishing a new release. I'll let you know once it's ready.

Regards,

Mati
