### ISSUE TITLE
Unable to get S&P 500 Index (^GSPC)

### ISSUE THREAD

**Issue by qnology** [matextrem/streamdeck-tickertap#4]
**Describe the bug**
Unable to get S&P 500 Index (^GSPC)

**To Reproduce**
Type Stocks
Ticker "^GSPC"

**Expected behavior**
Get S&P 500 price.

**Comment by matextrem** [comment]
Hey @qnology! That's not the right symbol as we're using `fvinz` as provider. The correct symbol would be `SPX`.

**Comment by qnology** [comment]
Thank you for the clarification. SPX works perfectly!
