### ISSUE TITLE
Ability to set Title. Currently "Disabled"

### ISSUE THREAD

**Issue by qnology** [matextrem/streamdeck-tickertap#5]
Select Type Commodity
Ticker "GC"

Currently display "GC" as title. Would like to set to "Gold"

Title is grayed out and "Disabled"

**Comment by matextrem** [comment]
Hey @qnology! Title is disabled as it only adds a text over the image and this is a unwanted behavior (see image attached). What we could do instead,  is to add a new field to add a custom ticker name. 

<img width="84" alt="image" src="https://github.com/matextrem/streamdeck-tickertap/assets/11525018/f6be4a93-a870-4e9a-bfe1-f97e21c239af">

**Comment by matextrem** [comment]
@qnology New version has been released with a new `Show as` field. 

You can download it from [here](https://github.com/matextrem/streamdeck-tickertap/releases/tag/v1.1.2).  I'll be asking ElGato team to update it so it can be downloaded from the store as well.

**Comment by qnology** [comment]
@matextrem, thank you so much for the quick turnaround. Tested new version and works perfectly!

You are killing it! Love this app.
