### ISSUE TITLE
[BUG] Crypto prices

### ISSUE THREAD

**Issue by belg1o** [matextrem/streamdeck-tickertap#6]
**Describe the bug**
Unable to set it to track crypto prices. Just keeps other settings.

**To Reproduce**
1. Select the crypto option
2. Set the currency to whatever currency of your choice (typed out per instructions)
3. Fails to set.

**Expected behavior**
Correctly retrieve the prices. 

**Screenshots**
![image](https://github.com/matextrem/streamdeck-tickertap/assets/11260048/9c8b6be6-79e3-4bb4-a889-2b2cbe95592f)

**Desktop (please complete the following information):**
 - OS: Win 11
 - App Version: 1.1.0

**Additional context**

**Comment by matextrem** [comment]
Help @belg1o. This was already resolved here https://github.com/matextrem/streamdeck-tickertap/issues/3

I will be contacting ElGato team to upload the new version in the store as well.
