### ISSUE TITLE
[FEATURE] Add ticker icons next to the name

### ISSUE THREAD

**Issue by belg1o** [matextrem/streamdeck-tickertap#7]
**Is your feature request related to a problem? Please describe.**
I'd like to have the company tickers appear next tot the name on the right side. 

Could use https://github.com/nvstly/icons database to pull the icons in. 

**Describe the solution you'd like**
![image](https://github.com/matextrem/streamdeck-tickertap/assets/11260048/aaf6d12c-4649-4f82-a3f4-7e288cb6a7d4)

**Describe alternatives you've considered**

**Additional context**

**Comment by matextrem** [comment]
Hey @belg1o! This is a great nice to have feature. We'll definitely work on having this for the next release. Thanks

**Comment by matextrem** [comment]
@belg1o I've published a new version including this change. You can download it from [here](https://github.com/matextrem/streamdeck-tickertap/releases/tag/v1.1.3)

Check it out and let me know what do yo think. Thanks!

**Comment by belg1o** [comment]
> @belg1o I've published a new version including this change. You can download it from [here](https://github.com/matextrem/streamdeck-tickertap/releases/tag/v1.1.3)
> 
> Check it out and let me know what do yo think. Thanks!

Thanks for the speedy integration! It looks great.
