### ISSUE TITLE
[FEATURE] Open URL/Chart on press

### ISSUE THREAD

**Issue by belg1o** [matextrem/streamdeck-tickertap#8]
**Is your feature request related to a problem? Please describe.**
It would be nice if on press we could have the option to direct it to a URL. 

**Describe the solution you'd like**
On short press: 
- Take me to Finviz stock profile for stocks/futures/commodities
- Take me to Coingecko for crypto 

On long press:
- Take me to TradingView of that asset

**Describe alternatives you've considered**
Allow user to input their own custom URLs depending on length of press.

**Additional context**

**Comment by matextrem** [comment]
Hey @belg1o! [v1.2.2](https://github.com/matextrem/streamdeck-tickertap/releases/tag/v1.2.2) has been released which includes long press behavior: Long pressed the key button redirects to the ticker website.
