### ISSUE TITLE
[BUG] Reversed performance signal

### ISSUE THREAD

**Issue by belg1o** [matextrem/streamdeck-tickertap#9]
**Describe the bug**
When crypto is selected, it is showing a reversed signal in the direction. 

**To Reproduce**
1. Select a crypto option 
2. Input token of choice
3. Compare direction to other stats

**Expected behavior**
Should be showing green since the last 24h have been positive performance

**Screenshots**
![image](https://github.com/matextrem/streamdeck-tickertap/assets/11260048/e11f4e29-8fb7-49bf-82f2-69989aeadcd5)

![image](https://github.com/matextrem/streamdeck-tickertap/assets/11260048/4fb24a4c-b44f-460d-896d-a5a8d21a53b5)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.1.3

**Additional context**

**Comment by matextrem** [comment]
Hey @belg1o ! Thanks for the report. 

I've updated the 1.1.3 version with the fix [here](https://github.com/matextrem/streamdeck-tickertap/releases/tag/v1.1.3)

Please remove the old version before installing this one in order to avoid sync issues with the app. 

Let me know if it fixes the issue.

**Comment by belg1o** [comment]
> [](https://github.com/matextrem/streamdeck-tickertap/releases/tag/v1.1.3)
> 
> Please remove the old version before installing this one in order to avoid sync issues with the app.

Did the trick! Thank you so much!

**Comment by belg1o** [comment]
> Hey @belg1o ! Thanks for the report.
> 
> I've updated the 1.1.3 version with the fix [here](https://github.com/matextrem/streamdeck-tickertap/releases/tag/v1.1.3)
> 
> Please remove the old version before installing this one in order to avoid sync issues with the app.
> 
> Let me know if it fixes the issue.

Did the trick! Thank you so much
